services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - qdrant-net

  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    ipc: host
    environment: 
      - VLLM_LOGGING_LEVEL=INFO
      - VLLM_DEBUG_LOG_API_SERVER_RESPONSE=TRUE

    command: --model openai/gpt-oss-20b --max-model-len 50000 --gpu-memory-utilization 0.7
      # command: --model leon-se/gemma-3-27b-it-qat-W4A16-G128 --max-model-len 4096 --max-num-seqs 1 --gpu-memory-utilization 0.75
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - /root/.cache/huggingface:/root/.cache/huggingface
      - /root/.cache/vllm:/root/.cache/vllm
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - qdrant-net

  neo4j:
    image: neo4j:community-bullseye
    container_name: neo4j
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687
    volumes:
      - neo4j_data:/data
      - /opt/neo4j/logs:/logs
      - /opt/neo4j/config:/config
      - /opt/neo4j/plugins:/plugins
    restart: always
    secrets:
      - neo4j_auth_file
    networks:
      - qdrant-net


volumes:
  qdrant_data:
  neo4j_data:

networks:
  qdrant-net:

configs:
  qdrant_config:
    content: |
      log_level: INFO

secrets:
  neo4j_auth_file:
    file: /opt/docker/neo4j/neo4j_auth.txt