services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334
    expose:
      - 6333
      - 6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - qdrant-net

#  whisper:
#    build:
#      context: ./whisper
#    image: whisper-app
#    container_name: whisper-container
#    volumes:
#      - ./lectures:/data
#      - ./whisper/models:/root/.cache/whisper
#    networks:
#      - qdrant-net

  vllm:
    image: vllm/vllm-openai:latest
    ipc: host

    command: --model openai/gpt-oss-20b --max-model-len 50000 --gpu-memory-utilization 0.7
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - /root/.cache/huggingface:/root/.cache/huggingface
      - /root/.cache/vllm:/root/.cache/vllm
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - qdrant-net

#  ollama:
#    image: ollama/ollama:latest
#    container_name: ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama:/root/.ollama
#    networks:
#      - qdrant-net
#
volumes:
  qdrant_data:

networks:
  qdrant-net:

configs:
  qdrant_config:
    content: |
      log_level: INFO
